using System;
using Sitecore.Diagnostics;
using Sitecore.SecurityModel;
using System.Management.Automation;
using System.IO;

public class SitecoreItemService
{
    public void ExecutePowerShellScript(string script)
    {
        try
        {
            // PowerShell execution setup
            using (var ps = PowerShell.Create())
            {
                // Add the script (the one generated by ChatGPT)
                ps.AddScript(script);

                // Execute the script
                var results = ps.Invoke();

                // Check for errors during execution
                if (ps.Streams.Error.Count > 0)
                {
                    // Handle errors
                    foreach (var error in ps.Streams.Error)
                    {
                        Log.Error(error.ToString(), this);
                    }
                }
                else
                {
                    // Log success
                    Log.Info("PowerShell script executed successfully.", this);
                }
            }
        }
        catch (Exception ex)
        {
            Log.Error("Error executing PowerShell script.", ex, this);
        }
    }
}
